#docker-compose -f docker-compose.media2.yaml up -d 
#docker-compose -f docker-compose.media2.yaml logs
version: '2'
services:
    plex:
        image: plexinc/pms-docker:latest
        #container_name: plex
        restart: unless-stopped
        ports:
            - "32400:32400/tcp"
            - "3005:3005/tcp"
            - "8324:8324/tcp"
            - "32469:32469/tcp"
            - "1900:1900/udp"
            - "32410:32410/udp"
            - "32412:32412/udp"
            - "32413:32413/udp"
            - "32414:32414/udp" 
        env_file: 
            - .env
        environment:
            - ADVERTISE_IP="http://10.40.1.114:32400/"
            - DEBUG=true
            #- PLEX_CLAIM 
            #- PLEX_UID=1000
            #- PLEX_GID=100
        volumes:
            - plexconfig:/config
            - plextranscode:/transcode
            - plexvideo:/data/videos
            - plexmusic:/data/music
            - plexpictures:/data/pictures
            - plexvidkids:/data/vidkids

    plex-storage:
        image: gavinjonespf/docker-minio-user
        command: server /export/
        ports:
            - "9000" 
        env_file: 
            - .env
        volumes:
            - plexconfig:/export/
        # environment:
        #     - MINIO_ACCESS_KEY=$UPLOAD_ACCESS_KEY
        #     - MINIO_SECRET_KEY=$UPLOAD_SECRET_KEY

volumes:
    plexconfig:
    plextranscode:
    plexvideo:
        driver: cifs
        driver_opts: 
            share: "nas-jones/videos"
    plexmusic:
        driver: cifs
        driver_opts: 
            share: "nas-jones/music"
    plexpictures:
        driver: cifs
        driver_opts: 
            share: "nas-jones/pictures"
    plexvidkids:
        driver: cifs
        driver_opts: 
            share: "nas-jones/videos-kids"
