version: '2'
services:
    plex-media:
        image: linuxserver/plex
        ports:
            - "1900:1900/udp"    
            - "5353:5353/udp"    
            - "32400:32400"    
            - "32400:32400/udp"    
            - "32469:32469"    
            - "32469:32469/udp"    
        env_file: 
            - .env
        volumes:
            - plexconfig:/config
            - plexvideo:/data/videos
            - plexmusic:/data/music
            - plexpictures:/data/pictures

volumes:
    plexconfig:
    plexvideo:
        driver: cifs
        driver_opts: 
            share: "nas-jones/videos"
    plexmusic:
        driver: cifs
        driver_opts: 
            share: "nas-jones/music"
    plexpictures:
        driver: cifs
        driver_opts: 
            share: "nas-jones/pictures"
