version: '2'
services:
    toolbox:
        image: gavinjonespf/docker-toolbox:latest  
        env_file: 
            - .env
        command: powershell
        env_file: 
            - .env
        environment:
            - DOCKER_NODE=${HOSTNAME}
        volumes:
            - workspace:/media/workspace
        stdin_open: true
        tty: true
        volumes:
            - plexconfig:/config
            - plexconfig2:/config2
            - plextranscode:/transcode
            - plexvideo:/data/videos
            - plexmusic:/data/music
            - plexpictures:/data/pictures
            - plexvidkids:/data/vidkids

volumes:
    plexconfig:
    plexconfig2:
    plextranscode:
    plexvideo:
        driver: cifs
        driver_opts: 
            share: "nas-jones/videos"
    plexmusic:
        driver: cifs
        driver_opts: 
            share: "nas-jones/music"
    plexpictures:
        driver: cifs
        driver_opts: 
            share: "nas-jones/pictures"
    plexvidkids:
        driver: cifs
        driver_opts: 
            share: "nas-jones/videos-kids"
